databases:
  - name: fallout_tracker_db
    databaseName: fallout_tracker_db
    user: fallout_tracker_user
    plan: free

services:
  - type: web
    name: fallout-tracker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fallout_tracker_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 