development:
  adapter: postgresql
  encoding: unicode
  database: fallout_tracker_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: fallout_tracker_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
